version: 2
 
sources:
  - name: qwt_raw
    description: source configuration for raw tables to be loaded
    database: "{{env_var('DBT_SOURCEDB','QWT_ANALYTICS')}}"
    schema: "{{env_var('DBT_SOURCESCHEMA','RAW')}}"
    tables: 
      - name: products
      - name: customer
      - name : orders
      - name : orderdetails
      - name : employees
      - name : offices
      - name : shipments
      - name : suppliers
    