{{ config(materialized = 'view', schema = 'reporting') }}
 
WITH FACT AS
(
    SELECT
    CUSTOMERID,
    MIN(ORDERDATE) AS MIN_ORDER_DATE,
    MAX(ORDERDATE) AS MAX_ORDER_DATE,
    SUM(QUANTITY) AS TOTAL_ORDERS,
    SUM(LINESALESAMOUNT) AS TOTAL_SALES
    FROM {{ref ('fct_orders')}}
    GROUP BY CUSTOMERID
),
CUST AS
(
    SELECT
    CUSTOMERID,
    COMPANYNAME,
    CONTACTNAME,
    CITY
    FROM {{ref ('dim_customers')}}
)
 
SELECT
CUST.COMPANYNAME AS CUST_COMPANY_NAME,
CUST.CONTACTNAME AS CUST_CONTACT_NAME,
CUST.CITY,
FACT.MIN_ORDER_DATE,
FACT.MAX_ORDER_DATE,
FACT.TOTAL_ORDERS,
FACT.TOTAL_SALES
FROM FACT
INNER JOIN CUST
ON FACT.CUSTOMERID = CUST.CUSTOMERID